refactor: venus-devtool: generate doc for api
filecoin-project/venus pull request #4749
Opened 2022-01-26 09:54 UTC by simlecode

## Related Issues

## Proposed Changes

no

## Additional Info

1. refactor: generate api doc tool
2. generate doc for messager api and wallet api

## Checklist

Before you mark the PR ready for review, please make sure that:
- [ ] All commits have a clear commit message.
- [ ] The PR title is in the form of of `<PR type>: <#issue number> <area>: <change being made>`
    - example: ` fix: #1234 mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_, _misc_, _perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _venus_, _venus-messager_, _venus-miner_, _venus-gateway_, _venus-auth_, _venus-market_, _venus-sealer_, _venus-wallet_, _venus-cluster_, _api_, _chain_, _state_, _vm_, _data transfer_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in [venus docs](https://venus.filecoin.io) or [Discussion Tutorials.](https://github.com/filecoin-project/venus/discussions/categories/tutorials)
- [ ] CI is green

2022-01-27 03:32 UTC, dtynn requested changes

2022-01-27 03:32 UTC, dtynn commented on venus-devtool/util/api_meta.go
> +
RPC Meta 是因为目前，我们对于 注册 RPC 服务端 Handler 所使用的命名空间比较混乱，为了兼容，而产生的。

在文档生成这个方面，是否可以考虑标准的输出文件名，类比 `proxy_gen.go`、`client_gen.go` 等，而无需逐一配置？

尽可能用约定替代人工配置

2022-02-08 03:36 UTC, simlecode commented on venus-devtool/util/api_meta.go
> +
统一输出文件名为 `method.md`

2022-02-09 01:28 UTC, hunjixin approved these changes

2022-02-09 01:29 UTC, merged