chore: change PR template
filecoin-project/venus pull request #5123
Opened 2022-07-22 03:29 UTC by LinZexiao

## Related Issues

involve https://github.com/filecoin-project/venus/issues/4971

## Proposed Changes

change PR template

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:
- [x] All commits have a clear commit message.
- [x] The PR title is in the form of of `<PR type>: <#issue number> <area>: <change being made>`
    - example: ` fix: #1234 mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_, _misc_, _perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _venus_, _venus-messager_, _venus-miner_, _venus-gateway_, _venus-auth_, _venus-market_, _venus-sealer_, _venus-wallet_, _venus-cluster_, _api_, _chain_, _state_, _vm_, _data transfer_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_
- [x] This PR has tests for new functionality or change in behaviour
- [x] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in [venus docs](https://venus.filecoin.io) or [Discussion Tutorials.](https://github.com/filecoin-project/venus/discussions/categories/tutorials)
- [x] CI is green

2022-07-22 03:48 UTC, Fatman13 requested changes

2022-07-22 03:48 UTC, Fatman13 commented on .github/pull_request_template.md
> +- [ ] 具有清晰明确的 commit message / All commits have a clear commit message.
commmit风格规范链接也可以加一个。 https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/git%E4%BD%BF%E7%94%A8/commit-message%E9%A3%8E%E6%A0%BC%E8%A7%84%E8%8C%83.md

2022-07-22 03:48 UTC, Fatman13 commented on .github/pull_request_template.md
这边按照 https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/github-project%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86.md 模版索性直接加上`resolve`关键词，省去PR提交人自己打了？

2022-07-22 05:20 UTC, Fatman13 requested changes

2022-07-22 05:20 UTC, Fatman13 commented on .github/pull_request_template.md
> +- [ ] 包含必要的测试用例 / This PR has tests for new functionality or change in behaviour
代码检查项的链接也可以加上 https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9

2022-07-22 06:16 UTC, 0x5459 commented
> ## 自查清单 (Checklist)
> 在你认为本 PR 满足被审阅的标准之前，需要确保 / Before you mark the PR ready for review, please make sure that:
> - [ ] 符合Venus项目管理规范中关于PR的[相关标准](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/PR%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83.md) / The PR follows the PR standards set out in the Venus project management guidelines
> - [ ] 具有清晰明确的 commit message / All commits have a clear commit message.
修改后的 PR 模版中的自查清单
> - [ ] 包含必要的测试用例 / This PR has tests for new functionality or change in behaviour
> - [ ] 包含必要的指南或文档 / If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included
> - [ ] 通过必要的检查项 / All checks are green

其中 "包含必要的测试用例", "包含必要的指南或文档" 从语义上来说是本次 PR 包含测试用例和文档才需要勾选，但我觉得这两个改成检查项 "包含必要的测试用例或不需要", "包含必要的指南或文档或不需要"，可能会更好。
参考案例库: [ant-design PULL_REQUEST_TEMPLATE CN](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md#%EF%B8%8F-%E8%AF%B7%E6%B1%82%E5%90%88%E5%B9%B6%E5%89%8D%E7%9A%84%E8%87%AA%E6%9F%A5%E6%B8%85%E5%8D%95), [ant-design PULL_REQUEST_TEMPLATE EN](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md#%EF%B8%8F-self-check-before-merge)

2022-07-22 06:25 UTC, LinZexiao commented on .github/pull_request_template.md
> +- [ ] 具有清晰明确的 commit message / All commits have a clear commit message.
我觉得可以直接都用close，因为fix和resolve具有特定语义

2022-07-22 06:26 UTC, LinZexiao commented on .github/pull_request_template.md
> +- [ ] 具有清晰明确的 commit message / All commits have a clear commit message.
赞同

2022-07-22 06:26 UTC, LinZexiao commented on .github/pull_request_template.md
> +- [ ] 包含必要的测试用例 / This PR has tests for new functionality or change in behaviour
赞同

2022-07-25 10:09 UTC, Fatman13 requested changes

2022-07-25 10:09 UTC, Fatman13 commented on .github/pull_request_template.md
> +- [ ] 包含相关的的指南以及[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3)或者不需要新增文档/ This PR has updated usage guidelines and docu
```suggestion
- [ ] 包含相关的的指南以及[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3)或者不需要新增文档 / This PR has updated usage guidelines and documentation or not need 
```

2022-07-25 10:09 UTC, Fatman13 commented on .github/pull_request_template.md
> +- [ ] 具有清晰明确的 [commit message](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/git%E4%BD%BF%E7%94%A8/commit-message%E9%A3%8E%
```suggestion
- [ ] 具有清晰明确的[commit message](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/git%E4%BD%BF%E7%94%A8/commit-message%E9%A3%8E%E6%A0%BC%E8%A7%84%E8%8C%83.md) / All commits have a clear commit message.
```

2022-07-25 10:09 UTC, Fatman13 commented
小的空格问题。

2022-07-26 02:34 UTC, Fatman13 approved these changes
LGTM

2022-07-26 02:44 UTC, merged